// Real browsers over immutable generated bytes. This is not model generation,
// desktop-window qualification or an aesthetic grade. Originals are read only.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {chromium, webkit} from 'playwright';
import {validateDesignProjects} from './design_project_cases.mjs';
import {designProjectScenarios, exerciseDesignProject} from './design_project_interactions.mjs';
import {measureProjectChoices} from './design_project_layout.mjs';
import {isDesignDeliveryComplete} from './design_comparison_report.mjs';
import {renderedContrast, doubleRenderedText, renderedReflow} from './design_preview_accessibility.mjs';

const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const json = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const hash = value => assert.match(value, /^[a-f0-9]{64}$/);
const MAX_FILES = 512, MAX_BYTES = 32 * 1024 * 1024;
const PROBLEM_LIMITS = {count:64, bytes:64*1024, detailBytes:4096};
function boundedProblemText(value) {
  const source=String(value); let text='',bytes=0;
  for(const character of source){const size=Buffer.byteLength(character);
    if(bytes+size>PROBLEM_LIMITS.detailBytes)break;
    text+=character;bytes+=size;
  }
  return {text,truncated:text.length<source.length};
}

export function validateProjectAuditInput(report, suite, suiteDigest, {partial = false} = {}) {
  const cases = validateDesignProjects(suite);
  for (const c of cases) assert.equal(typeof designProjectScenarios[c.interaction], 'function', `No oracle: ${c.interaction}`);
  assert.equal(report.suite?.sha256, suiteDigest, 'Frozen suite differs from generation inputs');
  assert.equal(report.suite.planned, 18);
  assert.ok(Array.isArray(report.suite.selected) && report.suite.selected.length > 0);
  assert.equal(new Set(report.suite.selected).size, report.suite.selected.length, 'Duplicate selected case');
  assert.ok(report.suite.selected.every(id => cases.some(c => c.id === id)), 'Unknown selected case');
  assert.equal(report.caseCount, report.suite.selected.length);
  assert.ok(Array.isArray(report.cases));
  assert.equal(new Set(report.cases.map(c => c.id)).size, report.cases.length, 'Duplicate native receipt');
  for (const result of report.cases) {
    const c = cases.find(c => c.id === result.id);
    assert.ok(c && report.suite.selected.includes(c.id), 'Unknown native receipt');
    assert.equal(result.prompt, c.prompt, 'Execution prompt differs from frozen brief');
    assert.equal(result.entry, c.entry); assert.equal(result.designSystemId, c.designSystemId);
  }
  hash(report.binarySha256); hash(report.model?.sha256);
  assert.ok(Number.isSafeInteger(report.model.bytes) && report.model.bytes > 0);
  assert.ok(report.engineIdentity && Object.keys(report.engineIdentity).length > 0, 'Missing engine identity');
  assert.ok(report.inference && report.memory, 'Missing actual generation settings');
  if (!partial) {
    assert.equal(report.interrupted ?? false, false, 'Interrupted run requires --completed-only');
    assert.equal(report.suite.selected.length, 18, 'Subset generation requires --completed-only');
    assert.equal(report.cases.length, 18, 'Missing generations; use --completed-only for a partial receipt');
    assert.ok(report.cases.every(c => !['running','pending','not-run'].includes(c.status)),
      'Unfinished generation requires --completed-only');
  }
  return cases;
}

// Bound the entire immutable export, not just index.html. Reject links/special
// files before reading. Only this in-memory map is exposed to the browser.
export function snapshotProject(workspace) {
  assert.ok(fs.lstatSync(workspace).isDirectory() && !fs.lstatSync(workspace).isSymbolicLink(), 'Workspace must be a real directory');
  const files = new Map(); let bytes = 0, entries = 0;
  const visit = (folder, relative = '') => {
    for (const name of fs.readdirSync(folder).sort()) {
      if (++entries > MAX_FILES) throw Error(`Project exceeds ${MAX_FILES} entries`);
      const file = path.join(folder, name), stat = fs.lstatSync(file), key = relative + name;
      assert.ok(!stat.isSymbolicLink(), 'Export contains a symlink: ' + key);
      if (stat.isDirectory()) { visit(file, key + '/'); continue; }
      assert.ok(stat.isFile(), 'Export contains a nonregular file: ' + key);
      assert.ok(bytes + stat.size <= MAX_BYTES, 'Project exceeds 32 MiB export bound');
      const data = fs.readFileSync(file), after = fs.lstatSync(file);
      for (const field of ['dev', 'ino', 'size', 'mtimeMs', 'ctimeMs']) assert.equal(after[field], stat[field], 'Export changed while reading: ' + key);
      assert.equal(data.length, stat.size); bytes += data.length; files.set(key, data);
    }
  };
  visit(workspace);
  assert.ok(files.has('index.html'), 'Missing index.html');
  return {files, bytes, hashes: Object.fromEntries([...files].map(([name, data]) => [name, sha(data)]))};
}

export async function serveProjectSnapshot(snapshot) {
  const mime = {'.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'application/javascript',
    '.mjs': 'application/javascript', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.woff2': 'font/woff2', '.woff': 'font/woff', '.json': 'application/json'};
  const preview = '<!doctype html><html><head><style>html,body{margin:0}iframe{width:100%;height:100vh;border:0;display:block}</style></head><body>'
    + '<iframe title="Design preview" sandbox="allow-scripts allow-forms" src="/project/index.html"></iframe></body></html>';
  const server = http.createServer((req, res) => {
    if (req.method !== 'GET') return res.writeHead(405).end();
    let url;
    try { url = new URL(req.url, 'http://localhost'); } catch { return res.writeHead(400).end(); }
    if (url.pathname === '/preview') return res.writeHead(200, {'Content-Type': 'text/html'}).end(preview);
    let key;
    try { key = decodeURIComponent(url.pathname.slice('/project/'.length)); } catch { return res.writeHead(400).end(); }
    if (!url.pathname.startsWith('/project/') || key.split('/').some(p => !p || p === '.' || p === '..') || key.includes('\\') || key.includes('\0')) return res.writeHead(403).end();
    const data = snapshot.files.get(key);
    if (!data) return res.writeHead(404).end();
    res.writeHead(200, {'Content-Type': mime[path.extname(key).toLowerCase()] || 'application/octet-stream',
      'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff'}).end(data);
  });
  server.requestTimeout = 5000; server.headersTimeout = 5000; server.maxConnections = 16;
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); });
  return {base: 'http://127.0.0.1:' + server.address().port,
    close: async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); }};
}

export async function auditProjectView(browser, target, c, settings, output, record, save) {
  const context = await browser.newContext({viewport: {width: settings.width, height: 1000}, colorScheme: settings.theme,
    reducedMotion: 'reduce', acceptDownloads: false});
  context.setDefaultTimeout(3000); context.setDefaultNavigationTimeout(10000);
  const problems = []; let page, closing;
  const capture=record.problemCapture={limits:{...PROBLEM_LIMITS},observed:0,bytes:2,exceeded:false};
  const closeContext=()=>closing??=context.close().then(()=>{record.cleanupComplete=true;})
    .catch(error=>{record.cleanupComplete=false;record.cleanupError=boundedProblemText(error.message).text;});
  const overload=reason=>{if(!capture.exceeded){capture.exceeded=true;capture.reason=reason;void closeContext();}};
  const problem=input=>{
    capture.observed=Math.min(Number.MAX_SAFE_INTEGER,capture.observed+1);
    if(capture.exceeded)return;
    const row={};let truncated=false;
    for(const [key,value] of Object.entries(input)){
      if(typeof value==='string'){const bounded=boundedProblemText(value);row[key]=bounded.text;truncated||=bounded.truncated;}
      else row[key]=value;
    }
    if(truncated)row.truncated=true;
    const bytes=Buffer.byteLength(JSON.stringify(row))+(problems.length?1:0);
    if(problems.length>=PROBLEM_LIMITS.count)return overload('count');
    if(capture.bytes+bytes>PROBLEM_LIMITS.bytes)return overload('bytes');
    problems.push(row);capture.bytes+=bytes;
    if(truncated)overload('detail');
  };
  const deadline=setTimeout(()=>{record.deadlineExceeded=true;void closeContext();},90000);
  const check = async (name, body, required = false) => {
    const result = {name, status: 'running'}; record.checks.push(result); save();
    try { assert.ok(!capture.exceeded,'Browser evidence limit exceeded');await body(); result.status = 'pass'; }
    catch (error) { result.status = 'fail'; result.error = boundedProblemText(error.message).text;
      if (required||capture.exceeded) throw error; }
    finally { save(); }
  };
  try {
    const expectedOrigin = new URL(target.url).origin;
    page=await context.newPage();
    // Playwright's blanket serviceWorkers:block initializer reads the forbidden
    // property in opaque frames and itself raises SecurityError. Block registration
    // only in our owning HTTP origin; opaque/file frames retain native isolation.
    await context.addInitScript(origin => {
      if (self.origin !== origin || self.origin === 'null' || !('serviceWorker' in navigator)) return;
      const workers = navigator.serviceWorker;
      Object.defineProperty(workers, 'register', {configurable: true, value: () => Promise.reject(
        new DOMException('Service workers are unavailable in the offline export audit', 'NotSupportedError'))});
    }, expectedOrigin);
    // No generated project may send requests to a sibling test endpoint, user
    // service or external site. data/blob resources stay local to its context.
    await context.route('**/*', async route => {
      const url = route.request().url();
      const allowed = url.startsWith(target.allowedPrefix) || settings.frame && url === target.url || /^(data|blob):/.test(url);
      try {
        if (!allowed) { problem({kind: 'external-request', url}); return await route.abort(); }
        return await route.continue();
      } catch(error) {
        // Closing an overloaded/deadline-expired context rejects its pending
        // routes. Other failures remain evidence and cannot become a PASS.
        if(!closing){problem({kind:'route-error',message:error.message});void closeContext();}
      }
    });
    await context.routeWebSocket('**/*', socket => {
      problem({kind: 'unexpected-websocket', url: socket.url()}); socket.close();
    });
    page.on('pageerror', error => problem({kind: 'script-error', message: error.message}));
    page.on('console', message => { if (message.type() === 'error') problem({kind: 'console-error', message: message.text()}); });
    page.on('response', response => { if (response.status() >= 400) problem({kind: 'missing-resource', url: response.url(), status: response.status()}); });
    page.on('websocket', socket => { problem({kind: 'unexpected-websocket', url: socket.url()}); });
    await page.goto(target.url, {waitUntil: 'load'});
    const scope = settings.frame ? page.frameLocator('iframe[title="Design preview"]') : page;
    if (settings.frame) {
      const frame = page.frames().find(f => f !== page.mainFrame()); assert.ok(frame);
      record.frameOrigin = await frame.evaluate(() => self.origin);
      assert.equal(record.frameOrigin, 'null', 'Generated page did not run in an opaque frame');
      assert.equal(await page.locator('iframe').getAttribute('sandbox'), 'allow-scripts allow-forms');
    } else assert.equal(new URL(page.url()).origin, expectedOrigin, 'Project navigated out of its export');
    await check('required initial content and Sample data are rendered', async () => {
      const body = (await scope.locator('body').innerText()).replace(/\s+/g, ' ').trim();
      assert.ok(body.length > 80); assert.match(body, /Sample data/i);
      for (const value of c.requiredText) assert.ok(body.includes(value.replace(/\s+/g, ' ')), 'Missing content: ' + value);
    });
    if (settings.textScale === 2) await doubleRenderedText(settings.frame ? page.frames().find(f => f !== page.mainFrame()) : page);
    await check('appearance follows the requested system colour scheme', async () => {
      record.appearance = await scope.locator('body').evaluate(body => {
        const rgb = str => (str.match(/[\d.]+/g) || []).map(Number);
        const root = getComputedStyle(document.documentElement), style = getComputedStyle(body);
        const base = rgb(root.backgroundColor), top = rgb(style.backgroundColor);
        const composite = (a, b) => a.slice(0, 3).map((v, i) => v * (a[3] ?? 1) + b[i] * (1 - (a[3] ?? 1)));
        const background = composite(top, composite(base, [255, 255, 255]));
        return {preferredDark: matchMedia('(prefers-color-scheme: dark)').matches, background,
          luminance: background.reduce((sum, value, i) => sum + value / 255 * [.2126, .7152, .0722][i], 0)};
      });
      assert.equal(record.appearance.preferredDark, settings.theme === 'dark');
      assert.equal(record.appearance.luminance < .5, settings.theme === 'dark', 'Appearance ignores selected light/dark preference');
    });
    await check('rendered text reflows and choice labels clear their indicators', async () => {
      const frame = settings.frame ? page.frames().find(f => f !== page.mainFrame()) : page;
      record.reflow = await renderedReflow(frame); assert.deepEqual(record.reflow, []);
      record.choices = await measureProjectChoices(scope);
      assert.deepEqual(record.choices.filter(r => !r.measured || !r.clearsIndicatorColumn), [], 'Choice label enters the indicator column');
    });
    await check('rendered text contrast is sufficient', async () => {
      const frame = settings.frame ? page.frames().find(f => f !== page.mainFrame()) : page;
      record.contrast = await renderedContrast(frame);
      assert.ok(record.contrast.length > 0); assert.deepEqual(record.contrast.filter(r => r.ratio + .01 < r.minimum), []);
    });
    await check('initial rendered screenshot retained', async () => {
      const name = `${c.id}-${settings.id}-initial.png`;
      await page.screenshot({path: path.join(output, name), fullPage: false});
      record.screenshots.push({file: name, sha256: sha(fs.readFileSync(path.join(output, name))), review: 'not_reviewed'});
    });
    if (settings.interactions) {
      try {
        await exerciseDesignProject(c, scope, page, async (name, body) => {
          await check(name, body, true);
          await check(name + ' — resulting layout', async () => {
            assert.deepEqual((await measureProjectChoices(scope)).filter(r => !r.measured || !r.clearsIndicatorColumn), []);
            const frame = settings.frame ? page.frames().find(f => f !== page.mainFrame()) : page;
            assert.deepEqual(await renderedReflow(frame), []);
          });
        });
        record.interactionStatus = 'pass';
      } catch (error) { record.interactionStatus = 'fail'; record.interactionError = boundedProblemText(error.message).text; }
    } else record.interactionStatus = 'not_run';
    await check('no missing assets, script errors or network dependencies', async () => { assert.deepEqual(problems, []); });
  } catch (error) {
    record.checks.push({name: 'browser view execution', status: 'fail', error: boundedProblemText(error.message).text});
  } finally {
    clearTimeout(deadline); await closeContext(); record.problems = problems;
    // A late error between the last check and close is still part of this
    // view. Success is published only after all owned browser events drain.
    record.checks.push({name:'browser events remain clean through teardown',
      status:!problems.length&&!capture.exceeded&&record.cleanupComplete?'pass':'fail'});
    record.status = record.checks.length > 0 && record.checks.every(c => c.status === 'pass') && !record.deadlineExceeded
      && (!settings.interactions || record.interactionStatus === 'pass') ? 'pass' : 'fail'; save();
  }
}

export async function auditDesignProjects(runArg, {partial = false} = {}) {
  const run = fs.realpathSync(runArg), source = json(path.join(run, 'report.json'));
  const suiteBytes = fs.readFileSync(path.join(run, 'frozen-cases.json')), suiteDigest = sha(suiteBytes), suite = JSON.parse(suiteBytes);
  const cases = validateProjectAuditInput(source, suite, suiteDigest, {partial});
  const completed = source.cases.filter(c => !['running','pending','not-run'].includes(c.status));
  assert.ok(completed.length > 0, 'No terminal generation receipt');
  const output = fs.mkdtempSync(path.join(run, 'project-audit-'));
  const report = {schema: 'dstudio.design-project-audit.v1', partial, startedAt: new Date().toISOString(),
    scope: 'Independent browser interactions on immutable generated exports. The opaque-frame test is an isolated preview harness, not the desktop app. No aesthetic score.',
    source: {label: source.label, reportSha256: sha(fs.readFileSync(path.join(run, 'report.json'))), suiteSha256: suiteDigest,
      binarySha256: source.binarySha256, modelSha256: source.model.sha256},
    auditor: Object.fromEntries(['design_project_audit.mjs', 'design_project_interactions.mjs', 'design_project_layout.mjs', 'design_preview_accessibility.mjs', 'design_comparison_report.mjs']
      .map(name => [name, sha(fs.readFileSync(new URL(name, import.meta.url)))])),
    limits: {filesPerProject: MAX_FILES, bytesPerProject: MAX_BYTES, browserViewMs: 90000, actionMs: 3000,
      browserProblems:PROBLEM_LIMITS},
    visualReview: 'not_reviewed', cases: []};
  const save = () => fs.writeFileSync(path.join(output, 'audit.json'), JSON.stringify(report, null, 2) + '\n');
  save();
  for (const c of cases) {
    const native = completed.find(row => row.id === c.id), record = {id: c.id, designSystemId: c.designSystemId, views: [], status: 'not_run'};
    report.cases.push(record); save();
    if (!native) continue;
    let server;
    try {
      assert.equal(native.status, 'idle', 'Native generation did not finish');
      assert.equal(native.generationPassed, true, 'Native delivery did not pass');
      assert.ok(isDesignDeliveryComplete(native),'Native output, cleanup and delivery identities do not agree');
      assert.ok(native.artifact && native.entryIsRegular && native.designSystemLoaded && !native.generationLimitReached);
      hash(native.entrySha256);
      const parent = path.join(run, c.id); assert.ok(!fs.lstatSync(parent).isSymbolicLink(), 'Case namespace is a symlink');
      const workspace = path.join(parent, 'workspace'), snapshot = snapshotProject(workspace);
      assert.equal(snapshot.hashes['index.html'], native.entrySha256, 'Generated entry changed after delivery');
      record.files = snapshot.hashes; record.bytes = snapshot.bytes;
      const exportRoot = path.join(output, 'exports', c.id); fs.mkdirSync(exportRoot, {recursive: true});
      for (const [name, bytes] of snapshot.files) {
        const file = path.join(exportRoot, name); fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, bytes, {flag: 'wx'});
      }
      server = await serveProjectSnapshot(snapshot);
      for (const [name, type] of [['chromium', chromium], ['webkit', webkit]]) {
        let browser;
        try {
          browser = await type.launch({headless: true});
          for (const theme of ['light', 'dark']) {
            for (const width of [320, 390, 768, 1440]) {
              const settings = {id: `${name}-${theme}-${width}`, engine: name, theme, width, textScale: 1, interactions: true};
              const view = {...settings, checks: [], screenshots: [], status: 'running'}; record.views.push(view); save();
              await auditProjectView(browser, {url: server.base + '/project/index.html', allowedPrefix: server.base + '/project/'}, c, settings, output, view, save);
            }
            for (const kind of ['text200', 'opaque', 'file-export']) {
              const settings = {id: `${name}-${theme}-${kind}`, engine: name, theme, width: 390,
                textScale: kind === 'text200' ? 2 : 1, frame: kind === 'opaque', interactions: true};
              const view = {...settings, checks: [], screenshots: [], status: 'running'}; record.views.push(view); save();
              const url = kind === 'file-export' ? pathToFileURL(path.join(exportRoot, 'index.html')).href
                : server.base + (settings.frame ? '/preview' : '/project/index.html');
              const allowedPrefix = kind === 'file-export' ? pathToFileURL(exportRoot + path.sep).href : server.base + '/project/';
              await auditProjectView(browser, {url, allowedPrefix}, c, settings, output, view, save);
            }
          }
        } catch (error) { record.views.push({engine: name, status: 'blocked', error: String(error.message), checks: [], screenshots: []}); }
        finally { if (browser) await browser.close(); }
      }
      assert.deepEqual(snapshotProject(workspace).hashes, snapshot.hashes, 'Audit changed original generated files');
      record.status = record.views.length === 28 && record.views.every(v => v.status === 'pass') ? 'pass' : 'fail';
    } catch (error) { record.status = 'fail'; record.error = String(error.message); }
    finally { if (server) await server.close(); save(); }
    console.log(`${c.id}: ${record.status}`);
  }
  report.finishedAt = new Date().toISOString();
  report.summary = {denominator: 18, passed: report.cases.filter(c => c.status === 'pass').length,
    failed: report.cases.filter(c => c.status === 'fail').length, notRun: report.cases.filter(c => c.status === 'not_run').length};
  report.status = !partial && report.summary.passed === 18 ? 'pass' : 'fail'; save();
  return {output, report};
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  assert.ok(process.argv[2], 'Pass the completed eighteen-project generation directory');
  assert.ok(!process.argv[3] || process.argv[3] === '--completed-only', 'Unknown audit option');
  const {output, report} = await auditDesignProjects(process.argv[2], {partial: process.argv[3] === '--completed-only'});
  console.log(`Independent project audit: ${output}\n${JSON.stringify(report.summary)}`);
  if (report.status !== 'pass') process.exitCode = 1;
}
