/* Execute the native schema reader, final parser and incremental SSE encoder.
 * Generated bytes are explicit fixtures; no inference or alternate tokenizer. */
#define Q36_SERVER_TEST
#define Q36_SERVER_TEST_NO_MAIN
#include "q36_server.c"

static chat_msgs replay_history(const tool_calls *calls, bool changed) {
    chat_msgs msgs = {0};
    chat_msg msg = {.role = xstrdup("assistant"), .content = xstrdup("")};
    for (int i = 0; i < calls->len; i++) {
        const tool_call *c = &calls->v[i];
        tool_calls_push(&msg.calls, (tool_call){.id = xstrdup(c->id),
            .name = xstrdup(c->name), .arguments = xstrdup(changed && !i
                ? "{\"changed_argument\":true}" : c->arguments)});
    }
    chat_msgs_push(&msgs, msg);
    return msgs;
}

static bool check_replay(const tool_calls *calls, const tool_schema_orders *orders,
                          bool batched, bool disk, bool changed) {
    server s = {.batched_mode = batched};
    pthread_mutex_init(&s.tool_mu, NULL);
    tool_memory_remember(&s, calls);
    if (disk) {
        FILE *fp = tmpfile(); uint64_t written = 0;
        if (!fp || !kv_tool_map_write(&s, fp, calls->raw_tool_text, &written) || !written) return false;
        tool_memory_free(&s.tool_mem);
        rewind(fp);
        int loaded = kv_tool_map_load_from_pos(&s, fp, NULL);
        fclose(fp);
        if (loaded != calls->len) return false;
    }
    chat_msgs msgs = replay_history(calls, changed);
    char *before = xstrdup(msgs.v[0].calls.v[0].arguments);
    tool_replay_stats stats = {0};
    tool_memory_attach_to_messages(&s, &msgs, &stats
#ifndef Q36_SCHEMA_TEST_LEGACY_API
        , orders
#endif
    );
    const char *attached = msgs.v[0].calls.raw_tool_text;
    bool okay = !strcmp(before, msgs.v[0].calls.v[0].arguments) && (changed
        ? !attached && stats.canonical == 1 && !stats.mem && !stats.disk
        : attached && !strcmp(attached, calls->raw_tool_text) && !stats.canonical &&
            (disk ? stats.disk : stats.mem) == 1);
    free(before); chat_msgs_free(&msgs);
    tool_memory_free(&s.tool_mem); pthread_mutex_destroy(&s.tool_mu);
    return okay;
}

int main(int argc, char **argv) {
    if (argc != 3) return 2;
    int step = atoi(argv[2]);
    if (step < 1 || step > 8192) return 2;
    char raw[8192];
    size_t n = fread(raw, 1, sizeof raw - 1, stdin);
    if (ferror(stdin) || !feof(stdin)) return 2;
    raw[n] = '\0';
    request r; request_init(&r, REQ_CHAT, 8192);
    r.has_tools = true; r.think_mode = Q36_THINK_NONE;
    const char *p = argv[1]; char *schemas = NULL;
    if (!parse_tools_value(&p, &schemas, &r.tool_orders)) return 3;
    free(schemas);
    tool_calls calls = {0}; char *content = NULL, *reasoning = NULL;
    char err[256] = {0}; const char *finish = "tool_calls"; bool recovered = false;
    bool parsed = parse_generated_message_for_response(raw, false, true, true,
        &finish, err, sizeof err, &content, &reasoning, &calls, &recovered
#ifndef Q36_SCHEMA_TEST_LEGACY_API
        , &r.tool_orders
#endif
    );
    if (!parsed || recovered) return 4;
    for (int i = 0; i < calls.len; i++) {
        char id[32]; snprintf(id, sizeof id, "fixture_tool_%d", i);
        calls.v[i].id = xstrdup(id);
    }
    buf result = {0}; buf_puts(&result, "{\"calls\":");
    append_tool_calls_json(&result, &calls, "fixture", &r.tool_orders);
    buf_puts(&result, ",\"anthropic\":");
    append_anthropic_content(&result, content, reasoning, &calls, "fixture", &r.tool_orders);
    buf_puts(&result, ",\"responses\":");
    append_responses_output(&result, "fixture", content, reasoning, &calls, finish);
    buf_puts(&result, ",\"replay\":[");
    for (int batch = 0; batch < 2; batch++) for (int disk = 0; disk < 2; disk++) {
        if (batch || disk) buf_putc(&result, ',');
        bool unchanged = check_replay(&calls, &r.tool_orders, batch, disk, false);
        bool changed = check_replay(&calls, &r.tool_orders, batch, disk, true);
        buf_printf(&result, "{\"batched\":%d,\"disk\":%d,\"unchanged\":%s,\"changed\":%s}",
                   batch, disk, unchanged ? "true" : "false", changed ? "true" : "false");
    }
    buf_putc(&result, ']');

    int pair[2];
    if (socketpair(AF_UNIX, SOCK_STREAM, 0, pair)) return 5;
    openai_stream stream; openai_stream_start(&r, &stream);
    buf events = {0};
    for (size_t at = 0; at < n;) {
        at += (size_t)step;
        if (at > n) at = n;
        char *prefix = xstrndup(raw, at);
        if (!openai_sse_stream_update(pair[0], NULL, &r, "fixture", &stream,
                                      prefix, at, false)) return 6;
        free(prefix);
        char *packet = read_socket_text(pair[1]);
        buf_puts(&events, packet); free(packet);
        if (events.len > 131072) return 7;
    }
    if (!openai_sse_finish_live(pair[0], NULL, &r, "fixture", &stream,
                               raw, n, &calls, finish, 0, 0)) return 8;
    shutdown(pair[0], SHUT_WR);
    char *packet = read_socket_text(pair[1]);
    buf_puts(&events, packet); free(packet);
    close(pair[0]); close(pair[1]);
    buf_puts(&result, ",\"sse\":"); json_escape(&result, events.ptr ? events.ptr : "");
    buf_printf(&result, ",\"layout\":{\"request\":%zu,\"schemaOrder\":%zu,\"property\":%zu,\"stream\":%zu}}\n",
               sizeof(request), sizeof(tool_schema_order), sizeof(r.tool_orders.v[0].prop[0]),
               sizeof(openai_tool_stream));
    fputs(result.ptr, stdout);
    free(content); free(reasoning); tool_calls_free(&calls);
    openai_stream_free(&stream); request_free(&r);
    buf_free(&events); buf_free(&result);
    return 0;
}
