import assert from 'node:assert/strict';
import {test} from 'node:test';
import {continuationTrace, continuationCode} from '../support/agent_continuation_oracle.mjs';

const token = (data, i = 1) => {
  const b = Buffer.isBuffer(data) ? data : Buffer.from(data);
  return `2026-09-12 12:00:00.000 token index=${i} id=42 bytes=${b.length} text="fixture" hex=${b.toString('hex')}`;
};
test('trace preserves output through compaction, including a split Unicode character', () => {
  const utf8 = Buffer.from('è');
  const trace = [
    '2026-09-12 12:00:00.000 tokens label=prefill_suffix start=0 len=5', token('not output'),
    '2026-09-12 12:00:00.000 prefill sync done tool_round=0 prompt=5 cached=0 suffix=5 rc=0 1.0 ms',
    token('A'), token(utf8.subarray(0, 1), 2),
    '2026-09-12 12:00:00.000 compaction-summary="This summary is not output"',
    '2026-09-12 12:00:00.000 compacted reason="generation reached compaction reserve" old=6000 new=2000 tail_start=5200 tail=800',
    token(utf8.subarray(1), 3), token('B', 4),
    '2026-09-12 12:00:00.000 generation finished tool_round=0 generated=4 carried=0 context_limited=0',
    token('not output'),
  ].join('\n');
  const r = continuationTrace(trace);
  assert.equal(r.response, 'AèB');
  assert.equal(r.tokens, 4);
  assert.deepEqual(r.rounds, [{round: 0, generated: 4, carried: 0}]);
  assert.equal(r.compactions.length, 1);
});
test('trace distinguishes later tool-round inputs and rejects truncated token bytes', () => {
  const begin = '2026-09-12 12:00:00.000 prefill sync done tool_round=0 prompt=5 cached=0 suffix=5 rc=0 1.0 ms';
  const r = continuationTrace([begin, token('yes'),
    '2026-09-12 12:00:00.000 tokens label=prefill_suffix start=0 len=1', token('input'),
    begin.replace('tool_round=0', 'tool_round=1'), token('!')].join('\n'));
  assert.equal(r.response, 'yes!');
  assert.throws(() => continuationTrace(begin + '\n' + token('a').replace('bytes=1', 'bytes=2')), /Truncated/);
});
test('code oracle retains generated bytes and accepts only the complete requested functions', () => {
  const code = 'int value_0(void) { return 0; }\nint value_1(void) { return 1; }';
  assert.equal(continuationCode(code, 2).code, code + '\n');
  assert.equal(continuationCode('```c\n' + code + '\n```', 2).code, code + '\n');
  for (const broken of [code.replace('return 1', 'return 2'), code.replace('value_1', 'value_0'),
    code.slice(0, -1), code + '\nExplanation', code.split('\n').reverse().join('\n'),
    code.replace(/^int /gm, '')])
    assert.throws(() => continuationCode(broken, 2));
});
